format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$docker_context\
$container\
$python\
$cmd_duration
$character"""

[git_metrics]
disabled = false
added_style = 'gray'
deleted_style = 'gray'

[git_status]
style = 'gray'

[git_branch]
style = 'cyan'

[character]
success_symbol = '[⋗](bold gray)'
error_symbol = '[⋗](bold red)'

[directory]
style = 'cyan'
